name: bobjobot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  nyxx: ^6.3.1
  html: ^0.15.4
  http: ^1.2.2
  path: ^1.9.0
  xml: ^6.5.0
  intl: ^0.19.0
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
